Core6Mvc/Controllers/EmployeeController.cs
using AutoMapper;
using Core6Mvc.Models.DTO.Employees;

using Microsoft.AspNetCore.Mvc;
using Northwind.Entities;

namespace Core6Mvc.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly NorthwindContext context;
        private readonly IMapper mapper;

        public EmployeeController(NorthwindContext context, IMapper mapper)
        {
            this.context = context;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            // Ekranda görünecek modelimizi olusturuyoruz
            List<EmployeeListDto> listDtos = new List<EmployeeListDto>();

            //Database'den Calisanlari Cekiyoruz
            var EmployeeList = context.Employees.ToList();


            //database'den Gelen Verileri EmployeelistDto 'ya teker teker atiyoruz
            //foreach (var employee in EmployeeList)
            //{
            //    EmployeeListDto listDto = new();
            //    listDto.Id = employee.EmployeeId;
            //    listDto.FirstName = employee.FirstName;
            //    listDto.LastName = employee.LastName;
            //    listDto.HireDate = employee.HireDate;
            //    listDto.Country = employee.Country;
            //    listDto.City = employee.City;
            //    listDto.HomePhone = employee.HomePhone;


            //    //Listeye ekliyoruz
            //    listDtos.Add(listDto);
            //}
            IList<EmployeeListDto> calisanlar = mapper.Map<IList<EmployeeListDto>>(EmployeeList);
            return View(calisanlar);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var calisan = context.Employees.FirstOrDefault(p => p.EmployeeId == id);


            EmployeeUpdateDto updateDto = mapper.Map<EmployeeUpdateDto>(calisan);
            return View(updateDto);
        }

        [HttpPost]
        public IActionResult Update(EmployeeUpdateDto input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }
            Employee gelen = mapper.Map<Employee>(input);

            context.Employees.Update(gelen);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            EmployeeCreateDto createDto = new();

            return View(createDto);
        }


        [HttpPost]
        public IActionResult Create(EmployeeCreateDto input)
        {
            if (ModelState.IsValid)
            {
                Employee emp = mapper.Map<Employee>(input);

                //emp.FirstName = input.FirstName;
                //emp.LastName = input.LastName;
                //emp.Title = input.Title;
                //emp.Country = input.Country;
                //emp.City = input.City;
                //emp.HireDate = input.HireDate;
                //emp.HomePhone = input.HomePhone;
                context.Employees.Add(emp);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(input);
        }
    }
}

Core6Mvc/Controllers/MyProductController.cs
using AutoMapper;
using Core6Mvc.Models.DTO.Products;
using Microsoft.AspNetCore.Mvc;
using Northwind.BL.Abstract;

namespace Core6Mvc.Controllers
{
    public class MyProductController : Controller
    {
        private readonly IProductManager productManager;
        private readonly IMapper mapper;

        public MyProductController(IProductManager productManager, IMapper mapper)
        {
            this.productManager = productManager;
            this.mapper = mapper;
        }
        public IActionResult Index()
        {
            var result = productManager.GetAllInclude(p => p.ProductId > 0,
                p => p.Category,
                p => p.Supplier).ToList();



            ICollection<ProductListDTO> products = mapper.Map<ICollection<ProductListDTO>>(result);
            return View(products);


        }
    }
}

Core6Mvc/Controllers/ShipperController.cs
using Microsoft.AspNetCore.Mvc;
using Northwind.Entities;

namespace Core6Mvc.Controllers
{
    public class ShipperController : Controller
    {
        private readonly NorthwindContext context;

        public ShipperController(NorthwindContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var result = context.Shippers.ToList();
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Shipper shipper = new();
            return View(shipper);
        }

        [HttpPost]
        public IActionResult Create(Shipper shipper)
        {
            if (ModelState.IsValid)
            {
                context.Shippers.Add(shipper);
                context.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(shipper);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var shipper = context.Shippers.Find(id);
            return View(shipper);
        }

        [HttpPost]
        public IActionResult Delete(Shipper shipper)
        {
            //var removeShipper = context.Shippers.FirstOrDefault(p => p.ShipperId == shipper.ShipperId);

            context.Remove(shipper);
            context.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Shipper shipper = context.Shippers.Find(id);
            return View(shipper);
        }

        [HttpPost]
        public IActionResult Update(Shipper shipper)
        {
            context.Update(shipper);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Core6Mvc/Views/Shared/PartialViews/footer.cshtml
<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Core6Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

Core6Mvc/Views/Shared/PartialViews/navbar.cshtml
 <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Core6Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shipper" asp-action="Index">Kargo Firmalari</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyProduct" asp-action="Index">Stoklar</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Çalişanlar</a>
                        </li>
                    </ul>
                </div>
            </div>
</nav>